### ISSUE TITLE
some streaming url found this issue in exo player in jet stream

### ISSUE THREAD

**Issue by thihas0ehtet** [android/tv-samples#119]
<img width="1422" alt="Screen Shot 2023-06-09 at 11 17 35 AM" src="https://github.com/android/tv-samples/assets/51940581/e3d2e027-41f1-4084-b4f1-84d727835040">

**Comment by vighnesh153** [comment]
I am unable to reproduce. Could you try restarting your device once and see if it works?

**Comment by sikandar210** [comment]
It sounds like you're having trouble with some streaming URLs in ExoPlayer on Jetstream. This could happen due to unsupported formats or server-side issues. If you're looking for an alternative, **[MagisTV](https://magistv-pc.net/)** might be a great solution for streaming. It offers a smooth experience with a variety of channels and content.Let me know if you need help setting it up!

**Comment by sikandar210** [comment]
[Pag-IBIG MP2 Calculator Online](https://pagibigmp2calculator.net/) is a user-friendly online tool designed to help Filipinos estimate their potential earnings from the Pag-IBIG MP2 Savings Program. By simply entering their desired monthly contribution and investment duration, users can quickly see projected dividends and total savings. This calculator makes financial planning easier, allowing members to maximize their savings strategy with accurate and instant calculations.

**Comment by sikandar210** [comment]
[TM SIM registration](https://tmsimregistration.pro/) is your go-to platform for hassle-free TM SIM registration in the Philippines. Whether you're a new or existing user, our website provides a seamless and secure way to comply with government regulations. Stay connected without the stress.
