### ISSUE TITLE
[LEANBACK] swiping in HorizontalGridView with mouse

### ISSUE THREAD

**Issue by danielto** [android/tv-samples#22]
Hello,

**Reference app:** 
Android TV application created by Android Studio via File / New / New Application / Android TV Activity. Android studio 3.6.

**Issue:**
When mouse is connected to STB and user wants to swipe in the HorizontalGridView (RowFragment), the content gets out of window and then returns back. 

The same issue is happening when application is running on mobile device and user wants to swipe the list quickly. 

![device-2020-03-02-140652](https://user-images.githubusercontent.com/10066429/75679449-f2189f00-5c8f-11ea-84b9-b580d35635a2.gif)

Is it possible to swipe the HorizontalGridView by mouse or touch screen without this behavior? 

Thank you in advance!

**Comment by IanGClifton** [comment]
It looks like this is an issue with the Leanback SDK. I've filed a bug at https://issuetracker.google.com/issues/150613588

**Comment by S0und** [comment]
Well, leanback is not designed to mouse/touch input. With a remote you can't scroll a row WITHOUT selecting the card, and while you use a mouse/touch you are doing exactly that, scrolling without selecting anything. You're expect it to work like a recycleview. 

Select AND scroll. Select the last visible element of the row and THEN scroll. It will work. 

Honestly i don't think this an issue, since the framework is not designed to be operated with a mouse/touch, since the prerequisite for leanback is NOT to have touch.

**Comment by IanGClifton** [comment]
Closing in favor of tracking at https://issuetracker.google.com/issues/150613588
