### ISSUE TITLE
SpeechRecognizer causing crash on SearchSupportFragment

### ISSUE THREAD

**Issue by NicolasDucom** [android/tv-samples#37]
For some devices that don't have microphones (Vestel 17OPS15, Zappiti 4K HDR etc...), the SpeechRecognizer service is causing my app to crash when using a SearchSupportFragment().
I don't have any logic regarding Voice recognition in my own code, the problem is caused by the `releaseRecognizer()` method called in onPause()  : 
`Caused by java.lang.IllegalArgumentException: Service not registered: android.speech.SpeechRecognizer$Connection@3cde2b3d
       at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1029)
       at android.app.ContextImpl.unbindService(ContextImpl.java:1808)
       at android.content.ContextWrapper.unbindService(ContextWrapper.java:551)
       at android.speech.SpeechRecognizer.destroy(SpeechRecognizer.java:408)
       at androidx.leanback.app.SearchSupportFragment.releaseRecognizer(SearchSupportFragment.java:440)
       at androidx.leanback.app.SearchSupportFragment.onPause(SearchSupportFragment.java:416)`
This issue is a more or less a [duplicate](https://github.com/googlearchive/androidtv-Leanback/issues/118) of an issue opened in the old androidtv-leanback repo, I wanted to know if any progress has been made regarding this problem, would it be simpler for me to open an issue on the Issuetracker ? 
I'm using `androidx.leanback:leanback:1.0.0`

**Comment by IanGClifton** [comment]
Hi Nicolas. Since this looks like an issue with the Leanback SDK itself, it'd be better to file this crash on the issue tracker, but you can add a link to the issue from here so that others who encounter it via these samples can go there and add more info or follow the issue. At this point, treating speech as a separate input is a bit outdated (e.g., Gboard for ATV can accept voice input directly and won't require each ATV app to request the audio permission), so I'm not sure if the fix is going to be graceful handling of devices without a mic or removing the special logic and leaning more on the keyboard.

**Comment by IanGClifton** [comment]
Fixed in https://issuetracker.google.com/issues/169936953
