### ISSUE TITLE
Navigation Component and Leanback example

### ISSUE THREAD

**Issue by luiscurini** [android/tv-samples#38]
Hi! I'm using a BrowseSupportFragment with PageRow, meaning that every item in the menu is a fragment. I have other activities where I show detail pages and the player. Is there a way to use the navigation components and have a single activity in Leanback while still using BrowseSupportFragment. 

If so could you provide an example?  This would be something similar to DrawerLayout which supports the navigation component. 

If this is not possible, would it be possible to use with the new LeanbackTabLayout?

**Comment by IanGClifton** [comment]
These types of general support questions are best asked on Stack Overflow because you can get a more detailed/nuanced answer (filing an issue here is meant for if there is a bug with these samples specifically). You can swap out the complete fragments the same as any other fragments. For example, if you were going from your browse fragment to a playback fragment: findNavController().navigate(BrowseFragmentDirections.actionBrowseFragmentToPlaybackFragment(video))

If you want to keep the left nav from BrowseSupportFragment while changing the content on the right with navigation components, that's not supported. It might be possible, but it's not an expected use case.

LeanbackTabLayout is essentially TabLayout but with dpad/focus improvements. Your LeanbackViewPager would provide whatever content you want to display and the LeanbackTabLayout lets you switch between content.

**Comment by luiscurini** [comment]
Hi, 

My question was mostly keeping the left nav bar from BrowseSupportFragment and using navComponents. Of course from BrowseFragmentDirections I could navigate to any other fragment in the nav graph. I was just wondering if there was something similar to the DrawerLayout and Nav component for BrowseSupportFragment. 

I'm sorry that I wrote this here, but Stackoverflow [android-tv] and [leanback] tags don't really receive many answers. I thought that as this repo contains samples of architecture components and leanback that it'd be a good place to ask this. 

However a LeanbackTabLayout mini sample would be nice even if it's TabLayout. Just to see if there are some specific things while implementing this for tv.

**Comment by IanGClifton** [comment]
Right now there isn't a TV component that is designed for keeping a menu on the left side while swapping out fragments on the right, though you could potentially build one using whatever layout you want on the left (if it's a small list, a LinearLayout is probably fine, otherwise you may want to use a RecyclerView) and swapping out fragments on the right by listening to the focus change. That does seem like a useful component to have, so feel free to suggest it in the issue tracker (https://issuetracker.google.com/issues?q=componentid%3A460758). There will be additional changes to Leanback by that engineering team in the future, so feature requests can help prioritize that work.

There are some demos for leanback components in the AndroidX repo and a simple Activity implementing LeanbackTabLayout is at https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:samples/SupportLeanbackDemos/src/main/java/com/example/android/leanback/TabLayoutActivity.java?q=leanbacktablayout

**Comment by TheDukerChip** [comment]
@IanGClifton 
Is there any plan for supporting AndroidX Navigation for Leanback components?
Would be great if you can point me to any official follow-up page

**Comment by Allan-Nava** [comment]
> @IanGClifton Is there any plan for supporting AndroidX Navigation for Leanback components? Would be great if you can point me to any official follow-up page

+1

**Comment by IanGClifton** [comment]
Sorry, I transferred to the DevRel team focused on Compose at the beginning of the year, so I don't know the latest on the plans for TV. I'd say, generally speaking, our focus across the board is on Compose, so I wouldn't expect significant updates to the view-based Leanback library.

**Comment by Allan-Nava** [comment]
> Sorry, I transferred to the DevRel team focused on Compose at the beginning of the year, so I don't know the latest on the plans for TV. I'd say, generally speaking, our focus across the board is on Compose, so I wouldn't expect significant updates to the view-based Leanback library.

Could you please share the projeect?
