### ISSUE TITLE
How to implement imaadsloader

### ISSUE THREAD

**Issue by hellfire1980** [android/tv-samples#8]
How to implement imaadsloader with the exoplayer example here.

**Comment by owahltinez** [comment]
I'm not sure I understand the question. There should be nothing special about the ExoPlayer used on TV, perhaps you should take a look at the examples under the ExoPlayer repo: https://github.com/google/ExoPlayer

**Comment by IanGClifton** [comment]
It sounds like this is more of a general implementation question than a question with these specific examples. StackOverflow (http://stackoverflow.com/questions/tagged/android-tv) is a better forum for those types of questions because you'll have a much larger audience to offer help, so I'm going to close this out.
